### ISSUE TITLE
PPL scores for replication/comparison?

### ISSUE THREAD

**Issue by searri** [quynhneo/detm-arxiv#2]
Thanks for open-sourcing this project! I'm interested in working with DETM so I've been experimenting with this and [your fork](https://github.com/quynhneo/DETM) of the original DETM code.

With the arXiv data, do you have a baseline perplexity score or other metric for me to compare results to? I'd like to make sure my modified code performs similarly to yours on the preprint Kaggle dataset before being too confident that it's working right.

**Comment by quynhneo** [comment]
hey thanks! I haven't touched this in a while, give me some time to dig it up

**Comment by searri** [comment]
Hello again! Bumping in case this got lost in the shuffle -- would be great to compare perplexity scores if you've got them handy!

**Comment by quynhneo** [comment]
Sorry, just reviewed. I actually have  never worked on that for this project, I am afraid you will have to start from scratch. i hope you ll share progress here.

**Comment by searri** [comment]
Ah, no problem! Thanks for checking.
